[build]
  # Build command for Vite projects
  command = "npm run build"
  
  # Directory to publish (Vite outputs to 'dist' by default)
  publish = "dist"
  
  # Node.js version
  NODE_VERSION = "18"
  
  # Ensure npm install runs before build
  NPM_FLAGS = "--production=false"

# Handle client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"